In [1]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

D:\anacinda\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


11493376/11490434 [==============================] - 30s 3us/step


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [4]:
test_images.shape

(10000, 28, 28)

In [5]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [6]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [7]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [8]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255


In [9]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [10]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 8s 135us/step - loss: 0.2587 - acc: 0.9253
Epoch 2/5
60000/60000 [==============================] - 7s 118us/step - loss: 0.1049 - acc: 0.9690
Epoch 3/5
60000/60000 [==============================] - 6s 103us/step - loss: 0.0697 - acc: 0.9795
Epoch 4/5
60000/60000 [==============================] - 7s 110us/step - loss: 0.0515 - acc: 0.9841
Epoch 5/5
60000/60000 [==============================] - 6s 108us/step - loss: 0.0394 - acc: 0.9883


In [11]:
 test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 86us/step


In [12]:
print('test_acc:', test_acc)

test_acc: 0.9811


In [13]:
print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [42]:
list_class=[ 0 for _ in range(0,10)]
print(list_class)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [43]:
for class_labels in train_labels:
    index=-1
    for label in class_labels:
        index=index+1
        #print("{0} {1}".format(index,label))
        if label:
            list_class[index]+=1
            
print(list_class)

[5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949]
